# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('grake_rcpparma_hello_world', PACKAGE = 'grake')
}

rcpparma_outerproduct <- function(x) {
    .Call('grake_rcpparma_outerproduct', PACKAGE = 'grake', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('grake_rcpparma_innerproduct', PACKAGE = 'grake', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('grake_rcpparma_bothproducts', PACKAGE = 'grake', x)
}

#' Singular value decomposition via RcppArmadillo
#' @param X matrix
#' @param method one of \code{"standard"} or \code{"dc"}
#' @export
arma_svd <- function(X, method = "standard") {
    .Call('grake_arma_svd', PACKAGE = 'grake', X, method)
}

